name: Deploy VPC


on:
  push:
    branches: [ "main" ]



jobs:
  build:
    runs-on: ubuntu-latest #windows-latest #mac-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: Initialize terraform
        run: |
          terraform init

          